#!/usr/bin/env node
/**
 * Style Dictionary v5 pipeline.
 *
 *   tokens/primitive/**.tokens.json   raw atoms (charcoal-900, amber-500, size-300, …)
 *   tokens/semantic.dark.tokens.json  default theme — emitted at :root
 *   tokens/semantic.light.tokens.json overrides — emitted at [data-theme="light"]
 *   tokens/component/**.tokens.json   sparse, references semantic
 *
 * Outputs:
 *   src/styles/generated/tokens.css       :root vars (primitives + dark semantic + component)
 *   src/styles/generated/tokens.light.css [data-theme="light"] overrides (light semantic)
 *   src/styles/generated/_tokens.scss     SCSS variables (for use in @media etc.)
 *   src/styles/generated/_tokens-map.scss flat SCSS map for breakpoint helpers
 *   DESIGN.generated.md                   markdown fragments concatenated into DESIGN.md
 */
import StyleDictionary from "style-dictionary";
import { formattedVariables } from "style-dictionary/utils";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";

const GENERATED_DIR = "src/styles/generated";
const DESIGN_AUTHORED = "DESIGN.authored.md";
const DESIGN_FRAGMENT = ".cache/DESIGN.generated.md";
const DESIGN_OUTPUT = "DESIGN.md";

const HEADER = (extra = "") =>
  `/**\n * THIS FILE IS GENERATED by build-tokens.mjs from tokens/.\n * Do not edit by hand — edit the source DTCG tokens and rerun \`pnpm tokens:build\`.\n${extra ? ` *\n * ${extra}\n` : ""} */\n\n`;

// -------- formats --------

StyleDictionary.registerFormat({
  name: "css/themed",
  format: async ({ dictionary, options }) => {
    const { outputReferences = true, selector = ":root" } = options;
    const header = HEADER();
    return (
      header +
      `${selector} {\n` +
      formattedVariables({
        format: "css",
        dictionary,
        outputReferences,
        usesDtcg: true,
      }) +
      "\n}\n"
    );
  },
});

StyleDictionary.registerFormat({
  name: "scss/variables-headered",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `$${t.name}: ${t.$value ?? t.value};`);
    return HEADER() + lines.join("\n") + "\n";
  },
});

StyleDictionary.registerFormat({
  name: "scss/map-tokens",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `  "${t.name}": ${t.$value ?? t.value},`);
    return (
      HEADER() +
      "@use 'sass:map';\n\n$tokens: (\n" +
      lines.join("\n") +
      "\n);\n\n@function token($name) { @return map.get($tokens, $name); }\n"
    );
  },
});

StyleDictionary.registerFormat({
  name: "markdown/design-fragment",
  format: ({ dictionary }) => {
    const groups = new Map();
    for (const token of dictionary.allTokens) {
      const head = token.path[0];
      if (!groups.has(head)) groups.set(head, []);
      groups.get(head).push(token);
    }

    const section = (title, tokens) => {
      const rows = tokens
        .map((t) => {
          const val = stringifyValue(t.$value ?? t.value);
          const desc = t.$description ?? t.description ?? "";
          return `| \`--${t.name}\` | \`${val}\` | ${desc} |`;
        })
        .join("\n");
      return `### ${title}\n\n| Token | Value | Notes |\n|---|---|---|\n${rows}\n`;
    };

    const sectionMap = {
      color: "## 2. Color\n\n",
      font: "## 3. Typography\n\n",
      size: "",
      lineHeight: "",
      letterSpacing: "",
      type: "",
      space: "## 5. Layout\n\n",
      border: "",
      radius: "",
      breakpoint: "",
      container: "",
      shadow: "## 6. Depth\n\n",
      duration: "",
      easing: "",
      z: "",
      card: "## 4b. Component tokens\n\n",
      chip: "",
    };

    let out = "<!-- GENERATED: do not edit by hand -->\n\n";
    const seenHeaders = new Set();
    const order = [
      "color",
      "font",
      "size",
      "lineHeight",
      "letterSpacing",
      "type",
      "space",
      "border",
      "radius",
      "breakpoint",
      "container",
      "shadow",
      "duration",
      "easing",
      "z",
      "card",
      "chip",
    ];

    for (const head of order) {
      if (!groups.has(head)) continue;
      const sectionTitle = sectionMap[head];
      if (sectionTitle && !seenHeaders.has(sectionTitle)) {
        out += sectionTitle;
        seenHeaders.add(sectionTitle);
      }
      out += section(prettyHead(head), groups.get(head)) + "\n";
    }
    out += "<!-- /GENERATED -->\n";
    return out;
  },
});

function prettyHead(h) {
  return (
    {
      color: "Color tokens",
      font: "Font families & weights",
      size: "Size scale",
      lineHeight: "Line heights",
      letterSpacing: "Letter spacing",
      type: "Type roles",
      space: "Spacing scale",
      border: "Border widths",
      radius: "Radii",
      breakpoint: "Breakpoints (min-width)",
      container: "Container widths",
      shadow: "Pixel shadows",
      duration: "Motion durations",
      easing: "Motion easings",
      z: "z-index scale",
      card: "Card",
      chip: "Chip",
    }[h] ?? h
  );
}

function stringifyValue(v) {
  if (v == null) return "";
  if (typeof v === "string" || typeof v === "number") return String(v);
  if (Array.isArray(v)) return v.join(", ");
  if (typeof v === "object") {
    return Object.entries(v)
      .map(([k, val]) => `${k}: ${val}`)
      .join("; ");
  }
  return String(v);
}

// -------- build pipelines --------

async function buildDarkAndPrimitives() {
  const sd = new StyleDictionary({
    log: { warnings: "warn", verbosity: "default" },
    source: [
      "tokens/primitive/**/*.tokens.json",
      "tokens/semantic.dark.tokens.json",
      "tokens/component/**/*.tokens.json",
    ],
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: `${GENERATED_DIR}/`,
        files: [
          {
            destination: "tokens.css",
            format: "css/themed",
            options: { outputReferences: true, selector: ":root" },
          },
        ],
      },
      scss: {
        transformGroup: "scss",
        buildPath: `${GENERATED_DIR}/`,
        files: [
          {
            destination: "_tokens.scss",
            format: "scss/variables-headered",
          },
          {
            destination: "_tokens-map.scss",
            format: "scss/map-tokens",
          },
        ],
      },
      markdown: {
        transformGroup: "css",
        buildPath: ".cache/",
        files: [
          {
            destination: "DESIGN.generated.md",
            format: "markdown/design-fragment",
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildLightOverrides() {
  // The "filtered references" warning is intentional here:
  // semantic.light references primitives that we deliberately exclude from this
  // file — primitives already live at :root in tokens.css, so var() refs resolve.
  const sd = new StyleDictionary({
    log: { warnings: "disabled", verbosity: "default" },
    source: ["tokens/primitive/**/*.tokens.json", "tokens/semantic.light.tokens.json"],
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: `${GENERATED_DIR}/`,
        files: [
          {
            destination: "tokens.light.css",
            format: "css/themed",
            // Emit only semantic tokens; primitives are already at :root.
            filter: (token) => token.filePath.includes("semantic.light.tokens.json"),
            options: {
              outputReferences: true,
              selector: '[data-theme="light"]',
            },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function composeDesignMd() {
  const authored = existsSync(DESIGN_AUTHORED)
    ? await readFile(DESIGN_AUTHORED, "utf8")
    : "# DESIGN.md\n\n(Authored sections missing — create DESIGN.authored.md.)\n\n";
  const generated = existsSync(DESIGN_FRAGMENT) ? await readFile(DESIGN_FRAGMENT, "utf8") : "";

  // Splice the generated block into a `<!-- GENERATED -->` placeholder if present,
  // otherwise append.
  let out;
  if (authored.includes("<!-- GENERATED:tokens -->")) {
    out = authored.replace(
      /<!-- GENERATED:tokens -->[\s\S]*?<!-- \/GENERATED:tokens -->/,
      `<!-- GENERATED:tokens -->\n${generated}\n<!-- /GENERATED:tokens -->`,
    );
  } else {
    out =
      authored +
      "\n\n---\n\n<!-- GENERATED:tokens -->\n" +
      generated +
      "\n<!-- /GENERATED:tokens -->\n";
  }
  await writeFile(DESIGN_OUTPUT, out, "utf8");
}

async function main() {
  await mkdir(GENERATED_DIR, { recursive: true });
  await mkdir(".cache", { recursive: true });
  await buildDarkAndPrimitives();
  await buildLightOverrides();
  await composeDesignMd();
  console.log("✓ tokens built");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
